### ISSUE TITLE
BIV 1.5 introduced multiple OS  hashes in show platform integrity

### ISSUE THREAD

**Issue by rymcmaho** [CiscoDevNet/BootIntegrityValidator#1]
BIV 1.5 introduced multiple OS  hashes in show platform integrity.  It would be great to for the software to be able to accept a BIV 1.5 show command

nd-ovld2#show platform sudi certificate sign nonce 12345
-----BEGIN CERTIFICATE-----
MIIDQzCCAiugAwIBAgIQX/h7KCtU3I1CoxW1aMmt/zANBgkqhkiG9w0BAQUFADA1
MRYwFAYDVQQKEw1DaXNjbyBTeXN0ZW1zMRswGQYDVQQDExJDaXNjbyBSb290IENB
IDIwNDgwHhcNMDQwNTE0MjAxNzEyWhcNMjkwNTE0MjAyNTQyWjA1MRYwFAYDVQQK
Ew1DaXNjbyBTeXN0ZW1zMRswGQYDVQQDExJDaXNjbyBSb290IENBIDIwNDgwggEg
MA0GCSqGSIb3DQEBAQUAA4IBDQAwggEIAoIBAQCwmrmrp68Kd6ficba0ZmKUeIhH
xmJVhEAyv8CrLqUccda8bnuoqrpu0hWISEWdovyD0My5jOAmaHBKeN8hF570YQXJ
FcjPFto1YYmUQ6iEqDGYeJu5Tm8sUxJszR2tKyS7McQr/4NEb7Y9JHcJ6r8qqB9q
VvYgDxFUl4F1pyXOWWqCZe+36ufijXWLbvLdT6ZeYpzPEApk0E5tzivMW/VgpSdH
jWn0f84bcN5wGyDWbs2mAag8EtKpP6BrXruOIIt6keO1aO6g58QBdKhTCytKmg9l
Eg6CTY5j/e/rmxrbU6YTYK/CfdfHbBcl1HP7R2RQgYCUTOG/rksc35LtLgXfAgED
o1EwTzALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUJ/PI
FR5umgIJFq0roIlgX9p7L6owEAYJKwYBBAGCNxUBBAMCAQAwDQYJKoZIhvcNAQEF
BQADggEBAJ2dhISjQal8dwy3U8pORFBi71R803UXHOjgxkhLtv5MOhmBVrBW7hmW
Yqpao2TB9k5UM8Z3/sUcuuVdJcr18JOagxEu5sv4dEX+5wW4q+ffy0vhN4TauYuX
cB7w4ovXsNgOnbFp1iqRe6lJT37mjpXYgyc81WhJDtSd9i7rp77rMKSsH0T8lasz
Bvt9YAretIpjsJyp8qS5UwGH0GikJ3+r/+n6yUA4iGe0OcaEb1fJU9u6ju7AQ7L4
CYNu/2bPPu8Xs1gYJQk0XuPL1hS27PKSb3TkL4Eq1ZKR4OCXPDJoBYVL0fdX4lId
kxpUnwVwwEpxYB5DC2Ae/qPOgRnhCzU=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIEPDCCAySgAwIBAgIKYQlufQAAAAAADDANBgkqhkiG9w0BAQUFADA1MRYwFAYD
VQQKEw1DaXNjbyBTeXN0ZW1zMRswGQYDVQQDExJDaXNjbyBSb290IENBIDIwNDgw
HhcNMTEwNjMwMTc1NjU3WhcNMjkwNTE0MjAyNTQyWjAnMQ4wDAYDVQQKEwVDaXNj
bzEVMBMGA1UEAxMMQUNUMiBTVURJIENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
MIIBCgKCAQEA0m5l3THIxA9tN/hS5qR/6UZRpdd+9aE2JbFkNjht6gfHKd477AkS
5XAtUs5oxDYVt/zEbslZq3+LR6qrqKKQVu6JYvH05UYLBqCj38s76NLk53905Wzp
9pRcmRCPuX+a6tHF/qRuOiJ44mdeDYZo3qPCpxzprWJDPclM4iYKHumMQMqmgmg+
xghHIooWS80BOcdiynEbeP5rZ7qRuewKMpl1TiI3WdBNjZjnpfjg66F+P4SaDkGb
BXdGj13oVeF+EyFWLrFjj97fL2+8oauV43Qrvnf3d/GfqXj7ew+z/sXlXtEOjSXJ
URsyMEj53Rdd9tJwHky8neapszS+r+kdVQIDAQABo4IBWjCCAVYwCwYDVR0PBAQD
AgHGMB0GA1UdDgQWBBRI2PHxwnDVW7t8cwmTr7i4MAP4fzAfBgNVHSMEGDAWgBQn
88gVHm6aAgkWrSugiWBf2nsvqjBDBgNVHR8EPDA6MDigNqA0hjJodHRwOi8vd3d3
LmNpc2NvLmNvbS9zZWN1cml0eS9wa2kvY3JsL2NyY2EyMDQ4LmNybDBQBggrBgEF
BQcBAQREMEIwQAYIKwYBBQUHMAKGNGh0dHA6Ly93d3cuY2lzY28uY29tL3NlY3Vy
aXR5L3BraS9jZXJ0cy9jcmNhMjA0OC5jZXIwXAYDVR0gBFUwUzBRBgorBgEEAQkV
AQwAMEMwQQYIKwYBBQUHAgEWNWh0dHA6Ly93d3cuY2lzY28uY29tL3NlY3VyaXR5
L3BraS9wb2xpY2llcy9pbmRleC5odG1sMBIGA1UdEwEB/wQIMAYBAf8CAQAwDQYJ
KoZIhvcNAQEFBQADggEBAGh1qclr9tx4hzWgDERm371yeuEmqcIfi9b9+GbMSJbi
ZHc/CcCl0lJu0a9zTXA9w47H9/t6leduGxb4WeLxcwCiUgvFtCa51Iklt8nNbcKY
/4dw1ex+7amATUQO4QggIE67wVIPu6bgAE3Ja/nRS3xKYSnj8H5TehimBSv6TECi
i5jUhOWryAK4dVo8hCjkjEkzu3ufBTJapnv89g9OE+H3VKM4L+/KdkUO+52djFKn
hyl47d7cZR4DY4LIuFM2P1As8YyjzoNpK/urSRI14WdIlplR1nH7KNDl5618yfVP
0IFJZBGrooCRBjOSwFv8cpWCbmWdPaCQT2nwIjTfY8c=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDfjCCAmagAwIBAgIDAaXTMA0GCSqGSIb3DQEBCwUAMCcxDjAMBgNVBAoTBUNp
c2NvMRUwEwYDVQQDEwxBQ1QyIFNVREkgQ0EwHhcNMTMwNzAyMTkyMTEwWhcNMjMw
NzAyMTkyMTEwWjBrMSgwJgYDVQQFEx9QSUQ6SVNSNDQ1MS1YL0s5IFNOOkZPQzE2
MzcwOUMzMQ4wDAYDVQQKEwVDaXNjbzEYMBYGA1UECxMPQUNULTIgTGl0ZSBTVURJ
MRUwEwYDVQQDEwxJU1I0NDUxLVgvSzkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQDPTpG5Xdn///mjJjf0/95DAw/HhYjIqDdgZfx8ZUWB8n3Z/FrM0stC
6WeyQwJTTg76Wh7NWQywbn7A1wgf88mrH0Hj3iDo+9w729oAMRYfrdBzT35Fm0/T
5oLkhJAhPfQN6sF0sTQP/63nWbhqsZBKj5cadLedudMrAXW0lCL2NEMcmtjWcn4Z
FKvp4kfaQUITigdtA//S14Zl/IH/lkGIBXs3k79YLjDKBh4YkCo5ugp6FUrubjne
Igc1xhYKR9E+oVH7wpEa/i6R6VrLpxxU4DqmXixLcWE7CvQQxLOawH/8vwJeo44A
IrobBFmX2NCqcDl52FJUNAIOZ3wO0SZnAgMBAAGjbzBtMA4GA1UdDwEB/wQEAwIF
4DAMBgNVHRMBAf8EAjAAME0GA1UdEQRGMESgQgYJKwYBAwEJFQICoDUTM0NoaXBJ
RD1VUUlTVTJsd0FRU2JBQUFBSEt2T2VTQXhOU0F4Tmpvd01qb3dNU0M2NEUwPTAN
BgkqhkiG9w0BAQsFAAOCAQEAeac2lMaJH6XDWLjkofA/O+WqFXPTvzcYxWBmzbAZ
Ie4yW33HGnTWsHvwk78WZtzQc3sRrMNAOgriJqncoHZu8MlH12KumQBRSTKwt0wJ
uA8HBkGgFdBugH1b3jvFsj9dJigeY5/UVsYQd8IKvR5duDcMpVypr6XjwzZJ26YG
+3pbL+MoXncAKfmK7wR5Rp3k1JrdRQJYoJssYSVMpD8bUVcouiKDl2cC9r2a0TH0
M6lrFdArun/uulRcX25ORI0TobOWiRVjcq0bjhmydsDL1A+OSwBCP08hI/O4dn7v
D3wkXTO1GiYoO9x38DW8cgGikHOTwMrKo/NxfU1FuXkttQ==
-----END CERTIFICATE-----

Signature version: 1
Signature:
634172F772B6DF844EF859C649B575736A66FF4343F487E7ED4D0EA2FB1B6A6A88BFC7A8592BDB62E3CD7E90B3A15866951695707C87B13C6B858B7675AC5B05FDD1121A01BCC6EF1B2C9C9A99F0413D955B0C3879A4B3468876954B8E867DF7BFA783B8195820DD61FBA9FD1308D21331DC764C7AFCA78FD9A5D9B5E9E7A0E6A9822AC624C2D9F6A33BE3C3226C6A8EBB65412DC46C4CEC0B34C588FFEA5B5FB0182AE60AC1EE8A2CE3C3C43E8C110FBC64507C95473BD81DC56B253F43E6D909F2BD151B752363444D67F4087A70975B36FC1365F06560AB12089F2CD38B086210B3E8193B647A2DD4F999D5DC9C94B5BC1FB792357038ACDB47A54567469F

nd-ovld2#show platform integrity sign nonce 12345
Platform: ISR4451-X/K9
Boot 0 Version: F01001R06.03c1d3d202013-01-18
Boot 0 Hash: 60FE9BB990E9ED6931D4CBB3BB9DD2703195B6710FE878C1C65CAE2A1FF84F11
Boot Loader Version: 16.12(2r)
Boot Loader Hash: DB7946CE3FE421F3B5B686C3F88D24135E5F6B95AD671609FC68845746AD8E38CC454126911F7AFF656A378CC74DC32BDFE35F8AC9302C07972F4B11F86851EE
OS Version: 17.04.01a
OS Hashes:
isr4400-universalk9.17.04.01a.SPA.bin: A5A505D87DD43534A7B3F30D7158D4AACE7B787105265288A4C62E44EFAFD9246C4A644104BE70C648492AEC4F415EBD988B0DE64ED7210058835E042AC1393F
isr4400-mono-universalk9.17.04.01a.SPA.pkg: E27B520E9373613AC5F8FEEFBC7FF42B426EA3F87367D8F293D0122B93CFB01D19F33434D3B0F8906D8FB6C978F1CC4A2894C864795E35EFB325ED4C5EC8D8BD
isr4400-firmware_nim_shdsl.17.04.01a.SPA.pkg: F4BCFA451A95C9EE7F2B8585C23FAD57E90CD01E72C03D3711EE821255A03E64894D64A2AFD2580FF64B65806709D371410F5C08C39732706EE172183AEDDF33
isr4400-firmware_sm_dsp_sp2700.17.04.01a.SPA.pkg: D2FF26E8F474346EC56091730AF8BD05FF109B9E3485B2F5BE57F1AB0DEDFE94C0A099B1DA46E7D3771EA753B077C4A258D08748B511B63B0FAE4917519F3361
isr4400-firmware_nim_cwan.17.04.01a.SPA.pkg: 87D6D4F9617506FF9F8C643EEEAED1524582B4C29BA9368EE2033FD3C697AC7D4C5DEF205A831CCD67269F38036830E9FF3FB983BBADB4F1EA4ABD64AB1F0B1A
isr4400-firmware_sm_async.17.04.01a.SPA.pkg: B4B8129BFB688D5357180767DF54652197B02C6F850A62AC15AD086B31C74FC27C4B1B349184621B4593142D1C5CB9BE59B83A4140591E875D7D4CFD9CE79BC6
isr4400-firmware_nim_ssd.17.04.01a.SPA.pkg: 7CD16A5A3ACE11E2981F3B1FA65383C0E8DDDF27C4FCB5CB369B4F3F636DD729EE92CAAAFF445D6D0DFC11F6DEA97B25743F61F0572E668D3046DD0CC868D490
isr4400-firmware_ngwic_t1e1.17.04.01a.SPA.pkg: 288479A89853337ACA0A439C9BE3F82E53BBF3FCFE9D504E3C98F762F2BDC54CD511189AAEF3C5224910A199A5CE4C7A06E5ED459134DBE6646A8BF833664A5E
isr4400-firmware_prince.17.04.01a.SPA.pkg: 83BA9FBB8DB3509A16AEB1D86EEC49DACB8BB672C4BF4A83F4C5542EA4AE39CD8704B1B8D19A1B3B8AF6648DC151D24E62D1D26DFAC47469F93C0BE9C4E9A38B
isr4400-firmware_sm_1t3e3.17.04.01a.SPA.pkg: 4EB9F1E7A903821D4C6B67D3BB171D3651622F5C9F7396A76C204309B2C0A22AFB7694752031ECAF72A0EDA809CEA239E60D3998F4866F2E7B8B5F75D84D03CA
isr4400-firmware_nim_async.17.04.01a.SPA.pkg: 3917D439F716B41AC69DF9EBE660212FF65705BC377483AA55DDABD7ED685F62A37C631EB6CE06B883C0C7945E118CDFAE686C062F6FAC3FB17C2D591E4D988B
isr4400-firmware_dsp_analogbri.17.04.01a.SPA.pkg: 55016D73ED0124C5D745C6D0C19DB23F0BBF96569BD399B8AD2E0E06E59B661BA1EBCB76E487FEEF5D1508BF3F9905F5F6DA5DF0851E5B815184B24BA65511BA
isr4400-firmware_nim_bri_st_fw.17.04.01a.SPA.pkg: E1ABE8AB7A64CDE1CED658423DCC9080B5EAD7C43C786D8924C9FA22D4C7A138BDEB377260889365BB40FBE2E4E279D95E5D6FC729746946F0098DBA72ECB0C9
isr4400-firmware_dreamliner.17.04.01a.SPA.pkg: B046B19B5A6B9DDC12743618C9793FBB6BEA4696F891FA7F3134821E105060BEFB6686B9EC164A7B0D9E7DECD4528F789FC4491A3535C8E11F61BEEC4CBB27E2
isr4400-firmware_dsp_tilegx.17.04.01a.SPA.pkg: 748B186C2EC34F3F9746F10DCD985B15D5D0473A3F354919882EDB53DFD01F5C1F78E431AEC3B9A36497D1D13BB9C1AE460D051114BEEB8479FEFA04AC3E5B10
isr4400-firmware_dsp_sp2700.17.04.01a.SPA.pkg: 49C96364C336BF6B1FE7F06BBE840A494F782AFB6836255BA0438A998F1EA976B7AE9425D3C301775185905FC65F3C555D8DE1D2CC29C87714A9F2C94D9DB355
isr4400-firmware_sm_10g.17.04.01a.SPA.pkg: AEC3206439A66628BD7F390FB13333FB2ECD8AA1308F669D22616534E3CCB3BADA82D6FB34E32FD6CAF121A3BB36BA8085C184EDEB935D11BDE2E468E96E3E49
isr4400-firmware_nim_ge.17.04.01a.SPA.pkg: B203295B95BA792791C3D81FCBF91B41C07CF4F87143816916F0815E36369F2C06BAA1C5B51D76D747B20164B9012E05C8E7AB7EC876237B70A811CAA20BB9DD
isr4400-firmware_nim_xdsl.17.04.01a.SPA.pkg: 56FE71B40D122FDDEC3D7E941581BBBB1CDA69C8A007EA3E2B22B23E06B8FF773DCD47FEFEE57E85B1A538A1439838C46BF2FF7C57651CDE8ABB73EB5EFEFD3E
PCR0: 77355C5CD678D8F62F2C3F2CB5AB4B9288509DEFA8381EE349637ECF42E99E52
PCR8: A7047F728F9C8FCDAE16AB7C2CD601203A188C538511F1EF77A4AFF5A784B37A
Signature version: 1
Signature:
6612DD27BEB92CC35EE21614E3920345FC6F808558AACE6AB95F58FAAEA90F20ADCA931BADB370A4911B962E5920F918108AA03BA48A61F253106DAF3BA2B071E8D26C8BADB3CAFA3C502B90F8C799A4ADBEF85D081126D064079E7E26DA25DF78D71D923694468490BA2383532E1FDCEAFA5F5088211F3BC2BF40C112B5679876564B439E91763CBFF7FBB6926E781091388FF5197AB627D273CA7960D09601E9D0ACCB6C8BFB01E15B5053B45B425AC4853DB56ABE83145E0FBC8FE3F3AF332DDBD045C22CCF3A2375C08DEE5F017A6A95467BEE1AF1718036E3B798BE79A7B6475A06225D1276E55C2AA0B0AEB1B17943DEF31FBC107545A1387C797C8015

**Comment by ministryofjay-cisco** [comment]
Fixed in version 1.5
